### ISSUE TITLE
Warning with Angular-18next with angular-cli

### ISSUE THREAD

**Issue by johnnykang** [Romanchuk/angular-i18next#7]
Hi,

Just wondering if you have came across this warning before ? The app still works with the warning but I wonder if there is a proper way to fix this warning.

WARNING in ./src/app/dashboard/dashboard.component.ts
102:277-296 "export 'ITranslationService' was not found in 'angular-i18next'
    at HarmonyImportSpecifierDependency._getErrors (/Volumes/Data/git-repo/sc-ols-live-reporting-ui/node_modules/webpack/lib/dependencies/HarmonyImportSpecifierDependency.js:65:15)
    at HarmonyImportSpecifierDependency.getWarnings (/Volumes/Data/git-repo/sc-ols-live-reporting-ui/node_modules/webpack/lib/dependencies/HarmonyImportSpecifierDependency.js:39:15)
    at Compilation.reportDependencyErrorsAndWarnings (/Volumes/Data/git-repo/sc-ols-live-reporting-ui/node_modules/webpack/lib/Compilation.js:701:24)
    at Compilation.finish (/Volumes/Data/git-repo/sc-ols-live-reporting-ui/node_modules/webpack/lib/Compilation.js:559:9)
    at applyPluginsParallel.err (/Volumes/Data/git-repo/sc-ols-live-reporting-ui/node_modules/webpack/lib/Compiler.js:506:17)
    at /Volumes/Data/git-repo/sc-ols-live-reporting-ui/node_modules/tapable/lib/Tapable.js:289:11
    at _addModuleChain (/Volumes/Data/git-repo/sc-ols-live-reporting-ui/node_modules/webpack/lib/Compilation.js:505:11)
    at processModuleDependencies.err (/Volumes/Data/git-repo/sc-ols-live-reporting-ui/node_modules/webpack/lib/Compilation.js:475:14)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)

**Comment by Romanchuk** [comment]
Hi, what version of angular and angular-i18next are you running?

**Comment by Romanchuk** [comment]
Is this still an issue?

**Comment by johnnykang** [comment]
Hi, I dun have access to my pc in the next 10 days. Will get back to you once I have access to my pc. Sorry about it.

**Comment by Romanchuk** [comment]
@johnnykang Please, update issue status

**Comment by Romanchuk** [comment]
Closed due lost of actual status
