### ISSUE TITLE
Unit test run error 

### ISSUE THREAD

**Issue by marcovmun** [Romanchuk/angular-i18next#95]
When updating to 14.1.0 from 14.0.5 I got this error when running my unit tests with `ng test`.

` An error was thrown in afterAll
  Uncaught ReferenceError: require is not defined
  ReferenceError: require is not defined
      at Module.82083 (http://localhost:9876/_karma_webpack_/webpack:/node_modules/.pnpm/angular-i18next@14.1.0_szl6vkehnoy2g5kp33txygyxui/node_modules/angular-i18next/fesm2015/angular-i18next.mjs:272:17)
      at __webpack_require__ (http://localhost:9876/_karma_webpack_/webpack:/webpack/bootstrap:19:1)
      at Module.95083 (http://localhost:9876/_karma_webpack_/main.js:3394:73)
      at __webpack_require__ (http://localhost:9876/_karma_webpack_/webpack:/webpack/bootstrap:19:1)
      at Module.55947 (http://localhost:9876/_karma_webpack_/main.js:208:97)
      at __webpack_require__ (http://localhost:9876/_karma_webpack_/webpack:/webpack/bootstrap:19:1)
      at Module.29011 (http://localhost:9876/_karma_webpack_/main.js:13:72)
      at __webpack_require__ (http://localhost:9876/_karma_webpack_/webpack:/webpack/bootstrap:19:1)
      at webpackContext (http://localhost:9876/_karma_webpack_/webpack:/src/ sync \.spec\.ts$:649:1)
      at Array.map (<anonymous>)
`

i18next: 21.10.0
i18next-http-backend: 1.4.5
Angular: 14.2.11

**Comment by Romanchuk** [comment]
It is issue [#91](https://github.com/Romanchuk/angular-i18next/issues/91)
It is fixed, but in beta version for now. I'll release stable version soon

**Comment by Romanchuk** [comment]
@marcovmun Stable version 14.2.0 released!

**Comment by marcovmun** [comment]
Thanks, build succeed again tonight with 14.2
